Style/FrozenStringLiteralComment: 
  Enabled: false
Style/MutableConstant:
  Enabled: false

Metrics/MethodLength:
  Max: 20
AllCops:
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes